//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisor
    {
        public int SupervisorId { get; set; }
        public int EmployeeId { get; set; }
        public int SupervisorEmployeeId { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
    }
}
